---
on:
  push:
    tags:
      - "*"

jobs:
  "publish":
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - run: |
          set -x
          sudo apt-get install -qqq xa65
          ./bootstrap
          ./configure
          make
          mkdir apple2
          cd src
          find . -name \*.a65 | xargs cp -v --parents -t ../apple2/
          cd -
          zip -r apple2sys apple2
          mkdir apple2-src
          cd src
          find . -name \*.s65 | xargs cp -v --parents -t ../apple2-src/
          cd -
          zip -r apple2sys-src apple2-src

      - uses: "softprops/action-gh-release@v1"
        with:
          files: |
            *.zip
